import { useMemo } from 'react';
import { FeatureFlags } from '../config/featureFlags';

export function useFeatureFlags() {
  return useMemo(() => ({
    ADS_ENABLED: FeatureFlags.ADS_ENABLED,
    PREMIUM_ENABLED: FeatureFlags.PREMIUM_ENABLED,
    REMOVE_ADS_FOR_PREMIUM: FeatureFlags.REMOVE_ADS_FOR_PREMIUM,
    ANALYTICS_ENABLED: FeatureFlags.ANALYTICS_ENABLED,
    OCR_ENABLED: FeatureFlags.OCR_ENABLED,
    PDF_COMPRESSION_ENABLED: FeatureFlags.PDF_COMPRESSION_ENABLED,
    PASSWORD_PROTECTION_ENABLED: FeatureFlags.PASSWORD_PROTECTION_ENABLED,
    WATERMARK_ENABLED: FeatureFlags.WATERMARK_ENABLED,
    CLOUD_STORAGE_ENABLED: FeatureFlags.CLOUD_STORAGE_ENABLED,
    AI_ENHANCEMENT_ENABLED: FeatureFlags.AI_ENHANCEMENT_ENABLED,
    DOWNLOAD_HISTORY_ENABLED: FeatureFlags.DOWNLOAD_HISTORY_ENABLED,
    DARK_MODE_ENABLED: FeatureFlags.DARK_MODE_ENABLED,
    MULTI_LANGUAGE_ENABLED: FeatureFlags.MULTI_LANGUAGE_ENABLED,
  }), []);
}
